### ISSUE TITLE
TypeError: Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by ericman314** [Thorium-Sim/thorium#1484]
## Detailed Description
I'm writing tests for the modules in `server/src/classes`. This is one of my test files:

```js
// server/tests/classes/coolant.test.js

import { System } from "../../src/classes/generic";
import Coolant from '../../src/classes/coolant';

describe('Coolant', () => {
  // ...
});
```

When I run the test from within the `server` directory using `npm test`, this is the output I get:

```
$ npm test

> thorium-server@1.0.21 test /home/eric/Documents/thorium/server
> jest --watchAll=false

 PASS  src/events/index.test.js
 PASS  src/schema/schema.test.js
 PASS  src/helpers/defaultSnapshot.test.js
 PASS  tests/classes/client.test.js
 PASS  tests/classes/generic/index.test.js
 PASS  src/helpers/paths.test.js
 PASS  tests/server/truth.test.js
 PASS  src/helpers/ipaddress.test.js
 PASS  src/helpers/subscriptionManager.test.js
 FAIL  tests/classes/coolant.test.js
  ● Test suite failed to run

    TypeError: Super expression must either be null or a function, not undefined

      13 |     setCoolant(coolant) {
      14 |       this.coolant = Math.min(1, Math.max(0, coolant));
    > 15 |     }
         |      ^
      16 |     setRate(rate) {
      17 |       this.heatRate = rate;
      18 |     }

      at _inherits (src/classes/generic/heatMixin.js:15:113)
      at src/classes/generic/heatMixin.js:19:5
      at HeatMixin (src/classes/generic/heatMixin.js:64:4)
      at Object.<anonymous> (src/classes/engine.js:167:27)
      at Object.<anonymous> (src/classes/index.js:7:15)
      at Object.<anonymous> (src/app.js:21:16)
      at Object.<anonymous> (src/classes/generic/index.js:16:12)
      at Object.<anonymous> (tests/classes/coolant.test.js:3:16)

Test Suites: 1 failed, 9 passed, 10 total
Tests:       4 skipped, 79 passed, 83 total
Snapshots:   0 total
Time:        1.526s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

However, if I import `Engine` _before importing_ `System`:

```js
import { Engine } from '../../src/classes/engine';
import { System } from "../../src/classes/generic";
import Coolant from '../../src/classes/coolant';

describe('Coolant', () => {
  // ...
});
```

Then there is no error and all the tests pass. What could be going on?

**Comment by alexanderson1993** [comment]
Seems like some kind of circular dependency. It might not be avoidable. I'll try to find a way to make this easier.

**Comment by alexanderson1993** [comment]
I've pushed an update to the root master branch which should take care of this. It's a simple setup script that loads the `App.js` file before every test. That should handle loading in any dependencies which the classes might need so this error doesn't happen.

I'm going to close this issue, but if it's still busted, comment here and I'll open it up again.
