### ISSUE TITLE
Mission Config, add task, admit patient

### ISSUE THREAD

**Issue by Xansta** [Thorium-Sim/thorium#2126]
## Detailed Description

![Screen Shot 2019-05-02 at 2 14 02 PM](https://user-images.githubusercontent.com/35241832/57100509-bebe5a00-6ce4-11e9-9827-a90a2f19e8e1.png)
Trying to add a task to admit a patient to sickbay and it seems to be stuck. I cannot tell if the zero out to the right of the Admit Patient item is related or not. Maybe I have to populate a list of potential patients somewhere to choose from before I can admit one.

Started in 1.2.16, updated to 1.2.17

Text from server window prior to update:
Last login: Sun Apr 21 13:18:34 on ttys001
Davids-MacBook-Pro-2:~ plaindavid$ /Users/plaindavid/Documents/Games/thorium/1.2.17/thorium-macos\ 2 ; exit;
Starting Thorium...

                                        
                  N7$                   
                D$$$$$$                 
               $$$$$$$$$                
              $$$$D  $$$$               
             7$$$     $$$$              
             $$$       $$$0           
            7$$$       $$$$             
            $$$$        $$$             
                 I????  $$$             
            ?????????? $$$$             
         ????????I     $$$0 $Z          
       ??????          $$$ $$$$$        
      ????   $Z$$     $$$$  OZ$$Z       
    D???I     Z$$Z    $$$     Z$$Z      
    ???        $$$$Z  $$       $$$Z     
   ????         OZ$$Z           $$$Z    
   ????        ?  $$$$$$        $$$$    
  7??????????????   $$$$$Z$Z$ZZZ$$$Z    
     ???????????       $Z$$$$$$$$$ZZ    
                                                                  
 _____ _                _                 
|_   _| |              (_)                
  | | | |__   ___  _ __ _ _   _ _ __ ___  
  | | | '_ \ / _ \| '__| | | | | '_ ' _ \ 
  | | | | | | (_) | |  | | |_| | | | | | |
  \_/ |_| |_|\___/|_|  |_|\__,_|_| |_| |_|

Client Server is now running on http://192.168.1.68:1337/client
Access the Flight Director on http://192.168.1.68:1337
GraphQL Server is now running on http://192.168.1.68:1338/graphql
🚀 Subscriptions ready at ws://192.168.1.68:1338/graphql
Error accessing task inputs for  Change Reactor Efficiency
TypeError: Cannot read property 'id' of undefined
    at /snapshot/thorium/build/tasks/reactor.js:0:0
    at Array.find (<anonymous>)
    at Object.input (/snapshot/thorium/build/tasks/reactor.js:0:0)
    at /snapshot/thorium/build/typeDefs/tasks.js:0:0
    at Array.reduce (<anonymous>)
    at valuesInput (/snapshot/thorium/build/typeDefs/tasks.js:0:0)
    at field.resolve (/snapshot/thorium/node_modules/graphql-extensions/dist/index.js:128:26)
    at resolveFieldValueOrError (/snapshot/thorium/node_modules/graphql/execution/execute.js:479:18)
    at resolveField (/snapshot/thorium/node_modules/graphql/execution/execute.js:446:16)
    at executeFields (/snapshot/thorium/node_modules/graphql/execution/execute.js:293:18)
Error accessing task values for  Change Reactor Efficiency
TypeError: Cannot read property 'id' of undefined
    at /snapshot/thorium/build/tasks/reactor.js:0:0
    at Array.find (<anonymous>)
    at Object.value (/snapshot/thorium/build/tasks/reactor.js:0:0)
    at /snapshot/thorium/build/typeDefs/tasks.js:0:0
    at Array.reduce (<anonymous>)
    at valuesValue (/snapshot/thorium/build/typeDefs/tasks.js:0:0)
    at field.resolve (/snapshot/thorium/node_modules/graphql-extensions/dist/index.js:128:26)
    at resolveFieldValueOrError (/snapshot/thorium/node_modules/graphql/execution/execute.js:479:18)
    at resolveField (/snapshot/thorium/node_modules/graphql/execution/execute.js:446:16)
    at executeFields (/snapshot/thorium/node_modules/graphql/execution/execute.js:293:18)
Error accessing task inputs for  Change Reactor Efficiency
TypeError: Cannot read property 'id' of undefined
    at /snapshot/thorium/build/tasks/reactor.js:0:0
    at Array.find (<anonymous>)
    at Object.input (/snapshot/thorium/build/tasks/reactor.js:0:0)
    at /snapshot/thorium/build/typeDefs/tasks.js:0:0
    at Array.reduce (<anonymous>)
    at valuesInput (/snapshot/thorium/build/typeDefs/tasks.js:0:0)
    at field.resolve (/snapshot/thorium/node_modules/graphql-extensions/dist/index.js:128:26)
    at resolveFieldValueOrError (/snapshot/thorium/node_modules/graphql/execution/execute.js:479:18)
    at resolveField (/snapshot/thorium/node_modules/graphql/execution/execute.js:446:16)
    at executeFields (/snapshot/thorium/node_modules/graphql/execution/execute.js:293:18)
Error accessing task values for  Change Reactor Efficiency
TypeError: Cannot read property 'id' of undefined
    at /snapshot/thorium/build/tasks/reactor.js:0:0
    at Array.find (<anonymous>)
    at Object.value (/snapshot/thorium/build/tasks/reactor.js:0:0)
    at /snapshot/thorium/build/typeDefs/tasks.js:0:0
    at Array.reduce (<anonymous>)
    at valuesValue (/snapshot/thorium/build/typeDefs/tasks.js:0:0)
    at field.resolve (/snapshot/thorium/node_modules/graphql-extensions/dist/index.js:128:26)
    at resolveFieldValueOrError (/snapshot/thorium/node_modules/graphql/execution/execute.js:479:18)
    at resolveField (/snapshot/thorium/node_modules/graphql/execution/execute.js:446:16)
    at executeFields (/snapshot/thorium/node_modules/graphql/execution/execute.js:293:18)
Downloading update...
Downloading: [====================] 100% Elapsed: 96.1s ETA: 0.0s
Moving new version into place
Download Complete. Close this window and open thorium-macos-1.2.17 for the updated version.

<img width="698" alt="Screen Shot 2019-05-02 at 2 20 45 PM" src="https://user-images.githubusercontent.com/35241832/57100876-9aaf4880-6ce5-11e9-822f-9e3c9c2245bc.png">

After finishing the update from the browser, the new file does not launch (see screenshot). Going back to try to download manually and launch again from new download.
<img width="426" alt="Screen Shot 2019-05-02 at 2 26 21 PM" src="https://user-images.githubusercontent.com/35241832/57101221-5a03ff00-6ce6-11e9-997f-bdabf266214f.png">

After downloading again, I get the error that the file was damaged when I try to launch

Any ideas?

**Comment by Emrix** [comment]
@Xansta, previously, I was able to download it, and but then it would be corrupted.  However, I just tried it right now, and I was able to download and install.  How exactly are you downloading it?  With Chrome?  Safari?

**Comment by Emrix** [comment]
And have you tried to populate a list of potential patients and then select one to admit yet?

**Comment by Xansta** [comment]
I'm in the process of trying to download again. Using Firefox, I go to the Thorium main page and click the download button, then click the big macOS button in the upper left. After it finished downloading, I go to the downloads folder and put the zip file (thorium-macos.zip) where I want to extract it and double click it. It extracts to a file thorium-macos which the operating system identifies as a Unix executable file. An invisible file (.DS_Store) also appears. Double clicking the thorium-macos file gives the error (captured again below)
<img width="481" alt="Screen Shot 2019-05-03 at 8 05 16 AM" src="https://user-images.githubusercontent.com/35241832/57139299-8b2e0f00-6d7a-11e9-87c8-9348bca2b18d.png">

How would I create a list of patients? I created one random crew. I'll patiently look for another area in which to create a list of potential patients :-)

**Comment by Xansta** [comment]
Chrome no longer supports my installed version of Mac OS (10.9)

**Comment by Xansta** [comment]
I downloaded Chrome version 38. The Thoriumsim main page comes up, but the download page is black. The download page is fine in Firefox.

**Comment by Xansta** [comment]
Interesting. When I type in the address manually in Chrome (https://thoriumsim.com/download), the download page appears briefly (less than a second), then the browser is refreshed, the url has a slash added to the end (https://thoriumsim.com/download/) and the page goes black.

**Comment by Xansta** [comment]
If I copy the url from Firefox (https://s3.amazonaws.com/thoriumsim/thorium-macos.zip), paste it in Chrome, the download starts, finishes and when I click the file from within Chrome, it auto-expands in the downloads folder. Double clicking _that_ gives me this result:
<img width="837" alt="Screen Shot 2019-05-03 at 8 53 31 AM" src="https://user-images.githubusercontent.com/35241832/57142035-3346d680-6d81-11e9-8557-916acc8b1d69.png">

This looks to me like the download is expecting the Thorium database or other artifacts to already be present locally in some fashion not handled by the download/extract process.

**Comment by Xansta** [comment]
This could also be my existing simulator/mission config attempt blowing up the local Thorium server instance. I don't want to delete my simulator if there's another way, but I will if I need to. 

Ideas? Suggestsions? Comments?

**Comment by alexanderson1993** [comment]
The damaged file problem has nothing to do with any of your data. It's just a problem with the file. No need to delete your simulator.

I'm afraid it's more likely some kind of compatibility issue with your outdated operating system. My goal with Thorium is to support the latest version of Chrome and any operating systems that can run it. Part of me wonders if these issues are related to you using MacOS 10.9.

**Comment by alexanderson1993** [comment]
With no activity on this issue for a while, I'm going to close it. If this is still a problem, holler and I'll open it up again.
